# -*- mode: shell-script -*-

# Display banner
test -f $HOME/.dotfiles/bash/greeting.sh && . $HOME/.dotfiles/bash/greeting.sh

# Reset sudo timeout
sudo -k

# Host specific settings
test -f $HOME/.dotfiles/bash/bashrc_$(hostname -s) && . $HOME/.dotfiles/bash/bashrc_$(hostname -s)

# Aliases
test -f $HOME/.dotfiles/bash/aliases.bash && . $HOME/.dotfiles/bash/aliases.bash

# Aliases
test -f $HOME/.aliases_local && . $HOME/.dotfiles/aliases_local

# Allow for .bash_local overrides
test -f "$HOME/.bashrc_local" && . $HOME/.bashrc_local

PATH=$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:/sbin

# Lang stuff
LC_ALL=en_US.UTF-8
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8

# Defaults
EDITOR="jed"
BROWSER="google-chrome"
PREVIEW="less"

# Don't check mail when opening terminal.
unset MAILCHECK

# Set this to the command you use for todo.txt-cli
export TODO="t"

test -f "/etc/bash_completion.d/password-store" && . /etc/bash_completion.d/password-store
test -f "/etc/bash_completion.d/mosh" && . /etc/bash_completion.d/mosh
test -f "/etc/bash_completion.d/docker.io" && . /etc/bash_completion.d/docker.io

test -f /usr/bin/keychain && eval $(keychain --noask --ignore-missing --eval id_rsa eerepoid EDEBB415)

# Don't freeze when ctrl+s in a shell
# https://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal
stty -ixon

test -f $HOME/.dotfiles/bash/prompt.bash && . $HOME/.dotfiles/bash/prompt.bash
